name: Synchronize to forked repo
on:
  push:
    branches:
      - develop

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.DEPLOY }}
          fetch-depth: 0
          ref: develop

      - name: Add remote-url
        run: |
          git remote add forked-repo https://baejb:${{ secrets.DEPLOY }}@github.com/baejb/FE
          git config user.name baejb
          git config user.email bjb6478@naver.com
      
      - name: Push changes to forked-repo 
        run: |
          git push -f forked-repo develop
      
      - name: Clean up
        run: |
          git remote remove forked-repo
